### PR TITLE
More last resorts (single versions)

### PR DESCRIPTION
**Pull request by zommerfelds**
CC0 => CC0-1.0

### CODE REVIEW

**Comment by kemitchell** [comment]
I like your thinking here!  I'm looking into what licenses-with-one-version your reductions find. We may prefer to bring in spdx-license-ids as a `devDependency` and generate a list on prepublish, or even hard-code.

**Comment by zommerfelds** [comment]
I can put the code to generate the list as a comment and hard code the output. Would that be good enough? I can look into automatic generation as well, but might make the process more complex.
BTW, the reason I'm adding this is because I'm running an analysis on published npm packages and just checking what the most common mistakes are and if your corrections make sense. The CC0 was the most common uncorrected one.

**Comment by kemitchell** [comment]
Great work!  Always a fan of empirical checks.  The metadata census I did, back in the day, lead right up to the pull requests getting SPDX expressions and validation in npm CLI.

Having given it a little more thought, I'm more and more in favor of packaging a dynamic computation along the lines you proposed. That does mean adding spdx-license-ids as a runtime dependency, but for a few reasons, I think that's fine:

1.  Earlier versions of this package `require`'d `spdx-license-ids`.
2.  `spdx-license-ids` is pretty small, as packages go. Most of the overhead of a package dependency is for resolution, another tarball, and so on, but small tarball counts for something.
3.  Many users of `sdpx-correct` are likely to have `spdx-license-ids` elsewhere in their dependency tree already.
4.  We're not talking about a whole lot of cycles or memory for the computation.

On the downside, `spdx-expression-parse` uses `spdx-license-ids` as a build dependency to generate its parser.  As a result, it takes a new publish of `spdx-expression-parse` to catch changes to `spdx-license-ids`. That means the `spdx-license-ids` that this package sees via `require`, and the one it gets transitively from `spdx-expression-parse`, may differ.

**Comment by zommerfelds** [comment]
Sure, I'm pretty neutral on that one, I don't have a preference. There is [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap), but I have never used and not sure if it is any good.

Do you propose any change here, or should we just go with what I proposed?

**Comment by kemitchell** [comment]
I'd appreciate you landing https://github.com/zommerfelds/spdx-correct.js/pull/1 if you haven't any objections there.

**Comment by zommerfelds** [comment]
Sorry I hadn't seen your PR there. Should be good now!

**Comment by zommerfelds** [comment]
Hi, just want to check back if you still think we should merge this?

**Comment by kemitchell** [comment]
@zommerfelds This looks good.

**Comment by zommerfelds** [comment]
@aviadatsnyk that's a good I idea. @kemitchel maybe we can take a look at the other open PRs before making a new version? I can help with the release too, but I don't have access to npm I think.

**Comment by kemitchell** [comment]
I will do a patch release shortly. 2.0.1, I believe.

There is a possible edge case here, if `spdx-license-ids` gets ahead of `spdx-expression-parse`.  Since `spdx-expression-parse` hard-codes the license ids, we may end up with different versions in the dependency tree.

I don't foresee any practical problems, short-term.  For long-term maintenance, it may be worth it to rewrite `spdx-expression-parse` to dynamically load the license list.

**Pull request merged**
